-- =========================================================================
-- Bug Triage Simulator: Live Global Realtime Leaderboard Schema
-- Paste and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- =========================================================================

-- 1. Create the leaderboard table
CREATE TABLE IF NOT EXISTS public.leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bugs INTEGER NOT NULL,
  score INTEGER NOT NULL,
  diff TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create index on score and bugs for high-speed top rank queries
CREATE INDEX IF NOT EXISTS idx_leaderboard_rank ON public.leaderboard (score DESC, bugs DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies: Allow public read and public insert
DROP POLICY IF EXISTS "Public can view leaderboard" ON public.leaderboard;
CREATE POLICY "Public can view leaderboard"
  ON public.leaderboard
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Public can insert high scores" ON public.leaderboard;
CREATE POLICY "Public can insert high scores"
  ON public.leaderboard
  FOR INSERT
  WITH CHECK (
    char_length(name) <= 14 AND
    score >= 0 AND
    bugs >= 0
  );

-- 5. Enable Realtime subscriptions for this table
ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
